LibraryApp/Controllers/UserLoginController.cs
using LibraryApp.Models.ViewModels;
using LibraryApp.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace LibraryApp.Controllers
{
	public class UserLoginController : Controller
	{
		LibraryDbContext db = new LibraryDbContext();
		public IActionResult Login()
		{
			ViewBag.Message = "";
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> LoginAsync(LoginViewModel model)
		{
			if (ModelState.IsValid)
			{
				var user = db.PanelUsers.FirstOrDefault(
					x => x.Email == model.Email
					&& x.Password == model.Password
					&& x.Status == true);

				#region Kullanıcı Yoksa
				if (user == null)
				{
					ViewBag.Message = "Lütfen bilgilerinizi kontrol edin";
					return View(model);
				}

				#endregion

				// Cookie kısmında verileri şifreli olarak tutması için hangi veriler 
				//olduğunu belirtiyoruz.
				var claims = new List<Claim>
				{
						new Claim(ClaimTypes.NameIdentifier, user.UserName),
						new Claim(ClaimTypes.Name, user.UserName),
						new Claim(ClaimTypes.Email, user.Email),
						new Claim("FullName", user.FullName),
						new Claim(ClaimTypes.Role, user.Role),
						new Claim("ImagePath", user.ImageUrl ?? "")
				};

				// Claimleri identity olarak işlemek için
				var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

				var authProperties = new AuthenticationProperties
				{
					AllowRefresh = true,
					// Refreshing the authentication session should be allowed.
					ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),
				};

				await HttpContext.SignInAsync(
					CookieAuthenticationDefaults.AuthenticationScheme,
								new ClaimsPrincipal(claimsIdentity),
								authProperties);
				return RedirectToAction("Index", "Management");
			}
			ViewBag.Message = "";
			return View(model);
		}

		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync();
			return RedirectToAction("Index", "Home");
		}
	}
}

LibraryApp/Views/Shared/_Footer.cshtml
<!-- Footer Start -->
<div class="container-fluid bg-img text-secondary" style="margin-top: 90px opacity:0.1;">
    <div class="container">
        <div class="row gx-5">
            <div class="col-lg-4 col-md-6 mb-lg-n5">
                <div class="d-flex flex-column align-items-center justify-content-center text-center h-100 bg-primary border-inner p-4">
                    <a href="index.html" class="navbar-brand">
                        <h1 class="m-0 text-uppercase text-white"><img src="~/img/kitap.png" alt="Kitap Resmi" width="70" height="40"></i>Bir Kitap <br/>Bir Yorum</h1>
                    </a>
                    <p class="mt-3">Bir Kitap Bir Yorum Kütüphanesi, zengin koleksiyonu ve geniş hizmet yelpazesi ile okuma tutkunlarına kapılarını açıyor. Kütüphanemiz, bilgiye erişimi kolaylaştırmak, öğrenmeyi teşvik etmek ve toplumun her kesimine hitap etmek amacıyla tasarlanmıştır.</p>
                </div>
            </div>
            <div class="col-lg-8 col-md-6">
                <div class="row gx-5">
                    <div class="col-lg-4 col-md-12 pt-5 mb-5">
                        <h4 class="text-primary text-uppercase mb-4">İletişim</h4>
                        <div class="d-flex mb-2">
                            <i class="bi bi-geo-alt text-primary me-2"></i>
                            <p class="mb-0">Çağlayan Mah. Kepez / Antalya</p>
                        </div>
                        <div class="d-flex mb-2">
                            <i class="bi bi-envelope-open text-primary me-2"></i>
                            <p class="mb-0">info@birkitapbiryorum.com</p>
                        </div>
                        <div class="d-flex mb-2">
                            <i class="bi bi-telephone text-primary me-2"></i>
                            <p class="mb-0">+90 537 642 19 44</p>
                        </div>
                        <div class="d-flex mt-4">
                            <a class="btn btn-lg btn-primary btn-lg-square border-inner rounded-0 me-2" href="https://www.instagram.com/gncbk"><i class="fab fa-twitter fw-normal"></i></a>
                            <a class="btn btn-lg btn-primary btn-lg-square border-inner rounded-0 me-2" href="https://www.facebook.com/emrullahkoccc?mibextid=eHce3h"><i class="fab fa-facebook-f fw-normal"></i></a>
                            <a class="btn btn-lg btn-primary btn-lg-square border-inner rounded-0 me-2" href="https://www.linkedin.com/in/emrullah-ko%C3%A7-a1527527b/"><i class="fab fa-linkedin-in fw-normal"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 pt-0 pt-lg-5 mb-5">
                        <h4 class="text-primary text-uppercase mb-4">Site Haritası</h4>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" asp-action="Index" asp-controller="Home"><i class="bi bi-arrow-right text-primary me-2"></i>Ana Sayfa</a>
                            <a class="text-secondary mb-2" asp-action="About" asp-controller="Home"><i class="bi bi-arrow-right text-primary me-2"></i>Hakkımızda</a>
                            <a class="text-secondary mb-2" asp-action="ContactUs" asp-controller="Home"><i class="bi bi-arrow-right text-primary me-2"></i>İletişime Geçin</a>
                            <a class="text-secondary" asp-action="Contact" asp-controller="Home"><i class="bi bi-arrow-right text-primary me-2"></i>İletişim</a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 pt-0 pt-lg-5 mb-5">
                        <h4 class="text-primary text-uppercase mb-4">Bülten</h4>
                        <p>Kütüphanemize son eklenen eserleri kaçırmayın! En yeni ve en çok talep gören kitaplar, her zevke hitap eden geniş bir yelpazede sizleri bekliyor.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid text-secondary py-4" style="background: #111111;">
    <div class="container text-center">
        <p class="mb-0">
            &copy; <a class="text-white border-bottom" asp-action="Index" asp-controller="Home">BirKitapBirYorum</a>. <br />Her hakkı saklıdır.
            Tasarımcı <a class="text-white border-bottom" href="https://www.instagram.com/gncbk">Emrullah KOÇ</a>
        </p>
    </div>
</div>
<!-- Footer End -->
<!-- Back to Top -->
<a href="#" class="btn btn-primary border-inner py-3 fs-4 back-to-top"><i class="bi bi-arrow-up"></i></a>

LibraryApp/Views/Shared/_Head.cshtml
<meta charset="utf-8">
<title>Bir Kitap Bir Yorum</title>
<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta content="Kitap, Kütüphane, Yazar, Tolstoy" name="keywords">
<meta content="Kitap Kütüphanesi" name="description">
<!-- Favicon -->
<link href="~/img/favicon.png" rel="icon">
<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Oswald:wght@500;600;700&family=Pacifico&display=swap" rel="stylesheet">
<!-- Icon Font Stylesheet -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
<!-- Libraries Stylesheet -->
<link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
<!-- Customized Bootstrap Stylesheet -->
<link href="~/css/bootstrap.min.css" rel="stylesheet">
<!-- Template Stylesheet -->
<link href="~/css/style.css" rel="stylesheet">

LibraryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
   <partial name="_Head"/>
</head>
<body>
    <partial name="_Topbar" />
    <partial name="_Navbar"/>
    @RenderBody();
    <partial name="_Footer" />
    <partial name="_Scripts"/>
</body>

</html>

LibraryApp/Views/Shared/_Navbar.cshtml
<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-dark navbar-dark shadow-sm py-3 py-lg-0 px-3 px-lg-0">
    <a href="index.html" class="navbar-brand d-block d-lg-none">
        <h1 class="m-0 text-uppercase text-white"><i class="fa fa-birthday-cake fs-1 text-primary me-3"></i>Bir Kitap Bir Yorum</h1>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto mx-lg-auto py-0">
            <a href="index.html" class="nav-item nav-link active">Home</a>
            <a href="about.html" class="nav-item nav-link">About Us</a>
            <a href="menu.html" class="nav-item nav-link">Menu & Pricing</a>
            <a href="team.html" class="nav-item nav-link">Master Chefs</a>
            <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                <div class="dropdown-menu m-0">
                    <a href="service.html" class="dropdown-item">Our Service</a>
                    <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                </div>
            </div>
            <a href="contact.html" class="nav-item nav-link">Contact Us</a>
        </div>
    </div>
</nav>
<!-- Navbar End -->

LibraryApp/Views/Shared/_Scripts.cshtml
 <!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/easing/easing.min.js"></script>
<script src="~/lib/waypoints/waypoints.min.js"></script>
<script src="~/lib/counterup/counterup.min.js"></script>
<script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

<!-- Template Javascript -->
<script src="~/js/main.js"></script>

LibraryApp/Views/Shared/_Topbar.cshtml
<!-- Topbar Start -->
<div class="container-fluid px-0 d-none d-lg-block">
    <div class="row gx-0">
        <div class="col-lg-4 text-center bg-secondary py-3">
            <div class="d-inline-flex align-items-center justify-content-center">
                <i class="bi bi-envelope fs-1 text-primary me-3"></i>
                <div class="text-start">
                    <h6 class="text-uppercase mb-1">Mail</h6>
                    <span>info@birkitapbiryorum.com</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4 text-center bg-primary border-inner py-3">
            <div class="d-inline-flex align-items-center justify-content-center">
                <a asp-action="index" asp-controller="Home" class="navbar-brand">
                    <h1 class="m-0 text-uppercase text-white">
                        <i>
                            <img src="~/img/kitap.png" alt="Kitap Resmi" width="70" height="40">
                        </i>Bir Kitap Bir Yorum
                    </h1>
                </a>
            </div>
        </div>
        <div  class="col-lg-4 text-center bg-secondary py-3">
            <div class="d-inline-flex align-items-center justify-content-center">
                <a class="bi bi-instagram fs-1 text-primary me-3" href="https://www.instagram.com/gncbk" ></a>
                <a asp-action="Login" asp-controller="UserLogin" class="btn btn-primary me-md-2" role="button">Giriş Yap</a>
            </div>
        </div>
    </div>
</div>
<!-- Topbar End -->